baseURL = 'http://hosting-aws-codebuild.s3-website-us-east-1.amazonaws.com/'
languageCode = 'en-US'
title = 'Hosting Test - AWS CodeBuild'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
disableKinds = ['RSS', 'taxonomy', 'term']
enableGitInfo = true

[build]
useResourceCacheWhen = 'never'

[languages.en]
contentDir = 'content/en'
languageCode = 'en-US'
languageName = 'English'
weight = 1

[languages.de]
contentDir = 'content/de'
languageCode = 'de-DE'
languageName = 'Deutsch'
weight = 2

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = '10'

[[menu.main]]
name = 'Articles'
pageRef = '/articles'
weight = '20'

[[menu.main]]
name = 'Posts'
pageRef = '/posts'
weight = '30'

[[module.imports]]
path = "github.com/jmooring/hugo-content"
